chore(cargo): update dependencies, set rust-version in Cargo.toml
This updates all our dependencies and solves a `cargo audit` failure:

  error: 1 vulnerability found!
  Crate:     rustls
  Version:   0.23.42
  Title:     TLS 1.3 handshake messages incorrectly accepted across encryption level boundaries
  Date:      2026-09-14
  ID:        RUSTSEC-2026-0285
  URL:       https://rustsec.org/advisories/RUSTSEC-2026-0285
  Severity:  5.3 (medium)
  Solution:  Upgrade to >=0.23.45

We were also missing a `rust-version` in Cargo.toml, which I've added.

Signed-off-by: Steven Noonan <steven@edera.dev>